### ISSUE TITLE
Aqui é um subtítulo, eu irei usar sempre "h2" ou h3". Para manter o padrão usa um desses para todos subtítulos. O que acha?

### ISSUE THREAD

**Issue by tiagobalsas** [LucasMLara/DevHut#9]
https://github.com/LucasMLara/DevHut/blob/077051b689148d7cb5b509b401c7ac6bc2e66396/bloco3/dia4/Stomadopoda.html#L27

**Comment by LucasMLara** [comment]
Acho válido!  coloca o H2 ou o H3 para esses títulos menores. eu usei o H3 direto pq ele mesmo já se estiliza num tamanho em que eu gostaria que fosse. o H2 é bom, mas não me atenderia especificamente nesse ponto.

eu irei terminar esse exercício amanhã pela manhã
